name: Deploy to EdgeOne

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy to EdgeOne Pages
        run: npx edgeone makers deploy ./dist -n childmath -t ${{ secrets.EDGEONE_API_TOKEN }} -e production
